const cars = [
  {name:"VW ID. Polo",trim:"Life 52 kWh",price:343500,priceDisplay:"343 500 kr",priceNote:"Levert Oslo; lokale tillegg kan komme",range:451,rangeDisplay:"451 km*",cargo:441,cargoDisplay:"441 l",charging:"105 kW / 24 min",tow:"1 200 kg",heatPump:"Standard",heatStatus:"green",status:"Mest komplett dokumentert",statusColor:"green",editorial:1,strength:"Bekreftet varmepumpe, fem seter, 1 200 kg henger og en sterk kombinasjon av rekkevidde og plass.",weakness:"Høyere pris enn de nærmeste utfordrerne. 105 kW DC er moderat i 2026.",question:"Endelig WLTP, faktisk levering og komplett totalpris lokalt."},
  {name:"Cupra Raval",trim:"Range Entry",price:299900,priceDisplay:"299 900 kr",priceNote:"Kampanje med frist 15.08.2026",range:440,rangeDisplay:"inntil 440 km",cargo:441,cargoDisplay:"441 l",charging:"105 kW / 24 min",tow:"Ubekreftet",heatPump:"Ubekreftet",heatStatus:"amber",status:"Pris må bekreftes",statusColor:"red",editorial:2,strength:"Polo-nær teknikk og samme bagasjevolum til en vesentlig lavere annonsert pris.",weakness:"Kampanjefristen er passert. Norsk varmepumpestatus er ikke bekreftet.",question:"Er kampanjen forlenget, og hva koster bilen med varmepumpe og ønsket utstyr?"},
  {name:"Škoda Epiq",trim:"52 kWh",price:339900,priceDisplay:"339 900 kr",priceNote:"Observert norsk startpris",range:441,rangeDisplay:"inntil 441 km",cargo:475,cargoDisplay:"475 l",charging:"105 kW / 23–24 min",tow:"1 200 kg",heatPump:"Ubekreftet i Norge",heatStatus:"amber",status:"Planlagt tidlig Q4",statusColor:"amber",editorial:3,strength:"Feltets største bekreftede bagasjerom og 1 200 kg hengervekt til nær Polo-pris.",weakness:"Varmepumpe er ikke dokumentert i norsk utstyrsliste i dette kildegrunnlaget.",question:"Hva er norsk standardutstyr og realistisk leveringsdato?"},
  {name:"Kia EV2",trim:"Long Range",price:309000,priceDisplay:"fra 309 000 kr",priceNote:"Variantutstyr må sammenlignes",range:448,rangeDisplay:"448 km*",cargo:400,cargoDisplay:">400 l",charging:"ca. 29–30 min",tow:"Ubekreftet",heatPump:"Ubekreftet",heatStatus:"amber",status:"Flere nøkkeltall foreløpige",statusColor:"amber",editorial:4,strength:"Lav startpris, stort 61 kWh-batteri og både 11 og 22 kW AC-lading.",weakness:"Kias kilde oppgir både 453 og 448 km. Bagasje, henger og varmepumpe må variantbekreftes.",question:"Hva får femseteren faktisk av bagasje, hengervekt og vinterutstyr?"},
  {name:"VW ID. Cross",trim:"Life 52 kWh",price:372500,priceDisplay:"372 500 kr",priceNote:"Dyrest; levering trolig 2027",range:427,rangeDisplay:"427 km",cargo:500,cargoDisplay:"475 + 25 l",charging:"ca. 23 min",tow:"Ubekreftet",heatPump:"Ubekreftet",heatStatus:"amber",status:"Produksjon senere",statusColor:"red",editorial:5,strength:"SUV-format, 475 liter bagasje og 25 liters frunk gir mest total lasteplass.",weakness:"Dyrest i feltet, kortere rekkevidde og 52 kWh-produksjon først sent i 2026.",question:"Er merplassen verdt prisen og ventetiden til 2027?"}
];
const grid=document.querySelector("#car-grid"),comparisonBody=document.querySelector("#comparison-body"),accordion=document.querySelector("#accordion"),controls=document.querySelectorAll("[data-sort]");
function renderCards(list){grid.innerHTML=list.map((car,index)=>`<article class="car-card"><span class="car-rank">${String(index+1).padStart(2,"0")}</span><h3>${car.name}</h3><span class="car-trim">${car.trim}</span><div class="car-price">${car.priceDisplay}</div><div class="car-price-note">${car.priceNote}</div><div class="range-bar" aria-label="${car.rangeDisplay} rekkevidde"><span style="width:${Math.min(100,car.range/5)}%"></span></div><div class="car-range"><span>WLTP</span><strong>${car.rangeDisplay}</strong></div><div class="status"><i class="dot dot-${car.statusColor}"></i>${car.status}</div></article>`).join("")}
function renderTable(){comparisonBody.innerHTML=cars.map(car=>`<tr><td>${car.name}<span class="cell-note">${car.trim}</span></td><td>${car.priceDisplay}<span class="cell-note">${car.priceNote}</span></td><td>${car.rangeDisplay}</td><td>${car.cargoDisplay}</td><td>${car.charging}</td><td>${car.tow}</td><td><span class="cell-status"><i class="dot dot-${car.heatStatus}"></i>${car.heatPump}</span></td></tr>`).join("")}
function renderAccordion(){accordion.innerHTML=cars.map((car,index)=>`<article class="detail"><button type="button" aria-expanded="false"><span class="detail-index">${String(index+1).padStart(2,"0")}</span><span class="detail-name">${car.name} <small>${car.trim}</small></span><span class="detail-summary">${car.status}</span><span class="detail-toggle" aria-hidden="true">+</span></button><div class="detail-content"><div class="detail-inner"><div class="detail-block"><h4>Styrke</h4><p>${car.strength}</p></div><div class="detail-block"><h4>Svakhet</h4><p>${car.weakness}</p></div><div class="detail-block"><h4>Må avklares</h4><p>${car.question}</p></div></div></div></article>`).join("");accordion.querySelectorAll(".detail button").forEach(button=>button.addEventListener("click",()=>{const item=button.closest(".detail"),content=item.querySelector(".detail-content"),isOpen=item.classList.toggle("open");button.setAttribute("aria-expanded",String(isOpen));content.style.maxHeight=isOpen?`${content.scrollHeight}px`:"0px"}))}
controls.forEach(control=>control.addEventListener("click",()=>{controls.forEach(item=>item.classList.remove("active"));control.classList.add("active");const sort=control.dataset.sort;const sorted=[...cars].sort((a,b)=>sort==="price"?a.price-b.price:sort==="range"?b.range-a.range:sort==="cargo"?b.cargo-a.cargo:a.editorial-b.editorial);renderCards(sorted)}));
renderCards(cars);renderTable();renderAccordion();
